version: '3.5'
services:
  postgresql:
    container_name: postgresql
    image: postgres:16-alpine
    ports:
      - '25432:5432'
    volumes:
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: playgroundb
  playground:
    build:
      context: .
    env_file:
      - .env
    entrypoint: '/usr/bin/java'
    command: '-jar -Dspring.profiles.active=postgresql app.jar'
    ports:
      - '8008:8080'
    depends_on:
      - "postgresql"
