spring:
  cache:
    cache-names: breaches
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  sql:
    init:
      mode: always

app:
  breaches:
    api:
      baseUrl: "https://haveibeenpwned.com/api/v2"
  security:
    local:
      users:
        - username: user1
          password: ${USER1_PWD}
          roles:
            - message.read
            - message.write
        - username: user2
          password: ${USER1_PWD}
          roles:
            - message.read
