spring:
  cache:
    cache-names: breaches,snyk
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  sql:
    init:
      mode: always

app:
  snyk:
    rest:
      api:
        token: "" # Needed in case ofqq authenticated Snyk API operations
  rest:
    api:
      name: "Playground API"
      description: "A playground implementation of a REST API"
      version: "0.1.0-SNAPSHOT"
  breaches:
    api:
      baseUrl: "https://haveibeenpwned.com/api/v2"
  security:
    local:
      users:
        - username: user1
          password: ${USER1_PWD}
          roles:
            - breach.read
            - message.read
            - message.write
            - snyk.read
        - username: user2
          password: ${USER2_PWD}
          roles:
            - message.read
