---
name: Docker CI

env:
  JAVA_VERSION: '17'
  JAVA_DIST: 'zulu'

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-docker.yml"
      - "Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/build-docker.yml"
      - "Dockerfile"

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build
        run:
          make docker-build