---
name: Code CI

env:
  JAVA_VERSION: '17'
  JAVA_DIST: 'zulu'

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "src/**"
      - "*.gradle.kts"
      - "Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "src/**"
      - "*.gradle.kts"
      - "Dockerfile"

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST}}

      - name: Code build
        run:
          ./gradlew build -x test

      - name: Docker build
        run:
          make docker-build